### ISSUE TITLE
Setup in custom path gives errors

### ISSUE THREAD

**Issue by Monkeybrain73** [anegostudios/vsmodtemplate#29]
Searching for VS in "d:\Vintagestory" ...

Something went wrong!
System.NullReferenceException: Object reference not set to an instance of an object.
   at vsmodtools.SetupCommand.CheckPath(String path)
   at vsmodtools.SetupCommand.Run(String[] args)
   at vsmodtools.Program.Main(String[] args)

**Comment by upchui** [comment]
Not only on custom paths...

VintageStory ModTools v1.5.7
 setup
Setting up workspace ...
Detecting Windows ...
Searching for VS in "C:\Users\Hutha\AppData\Roaming\Vintagestory" ...

Something went wrong!
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei vsmodtools.SetupCommand.CheckPath(String path)
   bei vsmodtools.SetupCommand.Run(String[] args)
   bei vsmodtools.Program.Main(String[] args)

Press any key to continue ...

**Comment by Th3Dilli** [comment]
vsmoddtools is deprecated since the switch to net7 and the template has been updated where it is no longer included.

The new template does take care of what vsmoddtools did see https://wiki.vintagestory.at/index.php/Modding:Setting_up_your_Development_Environment

that should get you setup and show how you can create new projects for modding
